version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK-DEFINITION-ARN>
        LoadBalancerInfo:
          ContainerName: awsome-books
          ContainerPort: 8080